### PR TITLE
FIX: Allow values to be 'reset' to null in index (fixes #203)

### LINKED ISSUE #203: Unable to remove a date from index
Given an index which includes a date (haven’t tested `addFulltextField` instead of `addFilterField`, but I suspect it’s the same):

```php
<?php

namespace App\Indexes;

use App\Model\Documents\Document;
use Firesphere\SolrSearch\Indexes\BaseIndex;

class DocumentIndex extends BaseIndex
{
    public function init()
    {
        $this->addClass(Document::class);
        $this->addFulltextField('Title');
        $this->addFulltextField('FileContent');
        $this->addFilterField('Embargo'); // Date
        $this->addFilterField('Expiry'); // Date
    }

    public function getIndexName()
    {
        return 'document';
    }
}
```

If you set a date against an object, it’s added to the index as expected. If you then remove that date (it’s set to `NULL` in the database), it’s not removed from the index.

`DocumentFactory` seems to explicitly filter out `null` values here: https://github.com/Firesphere/silverstripe-solr-search/blob/52398a4dcdb2df576f7cadc59c121337bfcbb276/src/Factories/DocumentFactory.php#L177-L179 I’m not sure if there’s any reason why?

### PR DESCRIPTION
**Pull request by kinglozzer**

### CODE REVIEW

File: src/Factories/DocumentFactory.php [hunk 1]
```diff
@@ -242,12 +239,12 @@ protected function getValuesForField($object, $options): array
...
      * @param array $options Custom options
      * @param string $type Type of Solr field
-     * @param DBField|string $value Value(s) of the field
+     * @param DBField|string|null $value Value(s) of the field
      */
     protected function addToDoc($doc, $options, $type, $value): void
     {
         /* Solr requires dates in the form 1995-12-31T23:59:59Z, so we need to normalize to GMT */
-        if ($type === 'tdate' || $value instanceof DBDate) {
+        if (($value && $type === 'tdate') || $value instanceof DBDate) {
```
Comment (kinglozzer) [inline src/Factories/DocumentFactory.php]: Without this change, `null` will be changed to `1970-01-01T00:00:00Z`

**Comment by Firesphere** [comment]
Failure on CircleCI is purely docs, so can be ignored.

**Comment by Firesphere** [comment]
Could you add a test for this @kinglozzer ? I feel it's useful to have it covered, instead of just checking it.

File: src/Factories/DocumentFactory.php (hunk 1 above)
Comment (Firesphere) [reply src/Factories/DocumentFactory.php]: Good change, but needs testing.
Also, the value can be 0 or false on purpose. This could possibly be hardened in the future. Not a high priority.

I would think `if (!$value || (other_value_checks))` might be sufficient?

**Comment by Firesphere** [comment]
@ssmarco Please make sure the failure is only on the docs. Docs failures are due to permissions, so if those fail, its fine.

**Comment by kinglozzer** [comment]
I’ve added a test that ensures `null` is passed as a value in the doc sent to Solr

File: src/Factories/DocumentFactory.php (hunk 1 above)
Comment (kinglozzer) [reply src/Factories/DocumentFactory.php]: True, but I would expect `0` and `false` values to already be corrected by the SilverStripe ORM/database before we reach this point?

Comment (Firesphere) [reply src/Factories/DocumentFactory.php]: Not really. 0 is treated as false, same as null. My suggestion would be wrong too. A hard check would be better
`($value !== false || $value !== null)` (something something PHP casting)

File: tests/unit/DocumentFactoryTest.php [hunk 2]
```diff
@@ -216,4 +216,41 @@ public function testDebug()
...
+
+        // Check the content is going to be removed from the index
+        $fields = $index->getFieldsForIndexing();
+        $docs = $factory->buildItems($fields, $index, $update);
+        $this->assertCount(1, $docs);
+        /** @var Document $doc */
+        $doc = $docs[0];
+        $fields = $doc->getFields();
+        $this->assertArrayHasKey('SiteTree_Content', $fields);
+        $this->assertNull($fields['SiteTree_Content']);
```
Comment (Firesphere) [inline tests/unit/DocumentFactoryTest.php]: Nice, thorough testing. Thanks :)
