### PR TITLE
Fix #143 unsetting ShowInSearch not removing object from Index

### LINKED ISSUE #143: searchQuery::setExclude() doesn't seem to work.
**Describe the bug**

`searchQuery::setExclude()` doesn't seem to work.

```
        $exclusions = [
            'SiteTree_ShowInSearch' => 0,
        ];
        $query = SearchQuery::create()
                ->setExclude($exclusions);
```

**To Reproduce**

1). [OK]  Hook up `SiteTree` into a `BaseIndex` subclass, configure and reindex (Tasks).
2). [OK] Ensure the results logic in Page/PageController/Whatever instantiates SearchQuery and sets an exclusion for "SiteTree_ShowInSearch" as per the above
3). [OK] Now toggle and save changes to this field in any Page's "Settings" tab.
4). [FAIL] Regardless of what this value is, the Page's "state" within the results remains unchanged.
5). [FAIL] Regardless of re-running the SolrIndexTask, this Page's "state" within the results remains the same

Additional: Weirdly, if I alter the exclusion thus:

```
'SiteTree_ShowInSearch' => 1,
```

The page in question re-appears. If it's set to zero, the page in question doesn't appear, despite my changing its "ShowInSearch" field value. (But weirder, other pages will still show for different searches.

**Expected behavior**

For changes to "'SiteTree_ShowInSearch" to be more consistent (or for me to understand how it _should_ work better!)

PHP 7.2 + `dev-master#7c78fb8c62618fbd50c926e5772457c827a6f4f0`

### PR DESCRIPTION
**Pull request by Firesphere**
When a page was indexed, and then set as "do not show in search", the page would not be properly removed from the index, causing it to show up in search despite the flag being unset.

### CODE REVIEW

File: src/Extensions/DataObjectExtension.php [hunk 1]
```diff
@@ -90,7 +90,12 @@ protected function pushToSolr(DataObject $owner)
         try {
             Versioned::set_reading_mode(Versioned::DEFAULT_MODE);
             $service->setInDebugMode(false);
-            $service->updateItems(ArrayList::create([$owner]), SolrCoreService::UPDATE_TYPE);
+            $type = SolrCoreService::UPDATE_TYPE;
+            // If the object should show in search, remove it
```
Comment (michalkleiner) [inline src/Extensions/DataObjectExtension.php]: `// If the object should NOT show in search...`

Comment (Firesphere) [reply src/Extensions/DataObjectExtension.php]: Blep, you're correct. Thinking is hard when on painkillers and all.
